DROP TABLE Person;
CREATE TABLE Person
(
    id            int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username      VARCHAR(100) NOT NULL,
    year_of_birth INT          NOT NULL CHECK ( year_of_birth > 1900 ),
    email         VARCHAR(100) NOT NULL UNIQUE,
    password      VARCHAR      NOT NULL,
    role          VARCHAR      NOT NULL
);



SELECT * FROM Person;

UPDATE Person SET role='ROLE_ADMIN' WHERE id = 1;

CREATE TABLE books
(
    id                              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                           VARCHAR,
    author                          VARCHAR,
    lang                            VARCHAR(100),
    document_size                   VARCHAR(200),
    year_of_publication             INTEGER,
    publishing_house                VARCHAR(200),
    country                         VARCHAR(200),
    number_of_pages                 INTEGER,
    availability_in_the_library     VARCHAR(50),
    availability_in_electronic_form VARCHAR(50),
    added                           VARCHAR(200),
    classification_id               VARCHAR(200),
    document_type                   VARCHAR(200),
    link_to_book                    VARCHAR(200),
    sub_category                    VARCHAR(200),
    global_category                 VARCHAR(200)
);

SELECT * FROM books;

